In [6]:
import numpy as np
x=np.array([1,2,4,5])
print(x)

[1 2 4 5]


In [8]:
x1=np.array([[1,2,4,5],[11,12,14,15]])
print(x1)

[[ 1  2  4  5]
 [11 12 14 15]]


In [10]:
x3=np.array([[[1,2,4,5],[11,12,14,15], [111,112,114,115]]])
print(x3)

[[[  1   2   4   5]
  [ 11  12  14  15]
  [111 112 114 115]]]


In [12]:
print(x.ndim,x1.ndim,x3.ndim)

1 2 3
